import { AuthorityType } from "@/types";

export const testUsers = [
  {
    userId: "yamada_taro",
    name: "山田 太郎",
    email: "yamada.taro@example.com",
    statusType: AuthorityType.ADMIN,
    birthDay: new Date(1985, 3, 15),
    profile: "山田太郎のプロフィールです。",
    description: "システム管理者として勤務しています。",
  },
  {
    userId: "suzuki_hanako",
    name: "鈴木 花子",
    email: "suzuki.hanako@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1990, 6, 20),
    profile: "鈴木花子のプロフィールです。",
    description: "マーケティング担当です。",
  },
  {
    userId: "tanaka_jiro",
    name: "田中 次郎",
    email: "tanaka.jiro@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1988, 11, 5),
    profile: "田中次郎のプロフィールです。",
    description: "営業部に所属しています。",
  },
  {
    userId: "kobayashi_ayumi",
    name: "小林 歩美",
    email: "kobayashi.ayumi@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1992, 1, 10),
    profile: "小林歩美のプロフィールです。",
    description: "経理担当です。",
  },
  {
    userId: "fujimoto_kenta",
    name: "藤本 健太",
    email: "fujimoto.kenta@example.com",
    statusType: AuthorityType.ADMIN,
    birthDay: new Date(1983, 9, 30),
    profile: "藤本健太のプロフィールです。",
    description: "開発チームリーダーです。",
  },
  {
    userId: "inoue_miki",
    name: "井上 美紀",
    email: "inoue.miki@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1991, 4, 18),
    profile: "井上美紀のプロフィールです。",
    description: "人事担当です。",
  },
  {
    userId: "saito_ryo",
    name: "斉藤 涼",
    email: "saito.ryo@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1987, 7, 22),
    profile: "斉藤涼のプロフィールです。",
    description: "技術サポートを担当しています。",
  },
  {
    userId: "takeda_emi",
    name: "武田 恵美",
    email: "takeda.emi@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1993, 2, 3),
    profile: "武田恵美のプロフィールです。",
    description: "広報担当です。",
  },
  {
    userId: "yamamoto_ken",
    name: "山本 健",
    email: "yamamoto.ken@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1989, 11, 11),
    profile: "山本健のプロフィールです。",
    description: "営業企画を担当しています。",
  },
  {
    userId: "nakamura_aya",
    name: "中村 彩",
    email: "nakamura.aya@example.com",
    statusType: AuthorityType.ADMIN,
    birthDay: new Date(1984, 0, 7),
    profile: "中村彩のプロフィールです。",
    description: "プロジェクトマネージャーです。",
  },
  {
    userId: "shimizu_kazuo",
    name: "清水 一郎",
    email: "shimizu.kazuo@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1986, 8, 25),
    profile: "清水一郎のプロフィールです。",
    description: "製品開発を担当しています。",
  },
  {
    userId: "morita_eri",
    name: "森田 恵理",
    email: "morita.eri@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1990, 5, 14),
    profile: "森田恵理のプロフィールです。",
    description: "デザイナーです。",
  },
  {
    userId: "kawasaki_shun",
    name: "川崎 俊",
    email: "kawasaki.shun@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1982, 3, 29),
    profile: "川崎俊のプロフィールです。",
    description: "サーバー管理者です。",
  },
  {
    userId: "hayashi_nao",
    name: "林 直子",
    email: "hayashi.nao@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1991, 10, 12),
    profile: "林直子のプロフィールです。",
    description: "カスタマーサポートを担当しています。",
  },
  {
    userId: "kondo_masato",
    name: "近藤 真人",
    email: "kondo.masato@example.com",
    statusType: AuthorityType.ADMIN,
    birthDay: new Date(1985, 6, 19),
    profile: "近藤真人のプロフィールです。",
    description: "システムアーキテクトです。",
  },
  {
    userId: "ito_yuka",
    name: "伊藤 由佳",
    email: "ito.yuka@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1987, 1, 4),
    profile: "伊藤由佳のプロフィールです。",
    description: "品質管理を担当しています。",
  },
  {
    userId: "fukuda_tomoya",
    name: "福田 友也",
    email: "fukuda.tomoya@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1993, 9, 9),
    profile: "福田友也のプロフィールです。",
    description: "営業部の新人です。",
  },
  {
    userId: "nakagawa_sana",
    name: "中川 紗奈",
    email: "nakagawa.sana@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1994, 7, 23),
    profile: "中川紗奈のプロフィールです。",
    description: "マーケティングアシスタントです。",
  },
  {
    userId: "okada_hiroshi",
    name: "岡田 弘",
    email: "okada.hiroshi@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1988, 4, 17),
    profile: "岡田弘のプロフィールです。",
    description: "サポートエンジニアです。",
  },
  {
    userId: "matsumoto_rika",
    name: "松本 莉佳",
    email: "matsumoto.rika@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1992, 0, 28),
    profile: "松本莉佳のプロフィールです。",
    description: "社内広報を担当しています。",
  },
  {
    userId: "ishikawa_shota",
    name: "石川 翔太",
    email: "ishikawa.shota@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1985, 9, 2),
    profile: "石川翔太のプロフィールです。",
    description: "開発チームメンバーです。",
  },
  {
    userId: "nakamura_miho",
    name: "中村 美穂",
    email: "nakamura.miho@example.com",
    statusType: AuthorityType.ADMIN,
    birthDay: new Date(1983, 11, 8),
    profile: "中村美穂のプロフィールです。",
    description: "プロジェクトリーダーです。",
  },
  {
    userId: "kato_ryo",
    name: "加藤 涼",
    email: "kato.ryo@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1987, 6, 16),
    profile: "加藤涼のプロフィールです。",
    description: "営業スタッフです。",
  },
  {
    userId: "yoshida_emi",
    name: "吉田 恵美",
    email: "yoshida.emi@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1990, 3, 27),
    profile: "吉田恵美のプロフィールです。",
    description: "企画部に所属しています。",
  },
  {
    userId: "takahashi_kou",
    name: "高橋 孝",
    email: "takahashi.kou@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1986, 5, 5),
    profile: "高橋孝のプロフィールです。",
    description: "経営企画を担当しています。",
  },
  {
    userId: "mori_naomi",
    name: "森 直美",
    email: "mori.naomi@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1989, 8, 13),
    profile: "森直美のプロフィールです。",
    description: "人事部に勤務しています。",
  },
  {
    userId: "shibata_kento",
    name: "柴田 健人",
    email: "shibata.kento@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1991, 7, 19),
    profile: "柴田健人のプロフィールです。",
    description: "技術サポートです。",
  },
  {
    userId: "oda_mayu",
    name: "小田 真由",
    email: "oda.mayu@example.com",
    statusType: AuthorityType.USER,
    birthDay: new Date(1994, 10, 24),
    profile: "小田真由のプロフィールです。",
    description: "広報担当です。",
  },
];
